apiVersion: app/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: cntsp/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPreset
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>